# Generated by Django 3.2.7 on 2021-10-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='manual',
            field=models.BooleanField(default=False),
        ),
    ]
