# Generated by Django 4.1 on 2022-09-19 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_usuario_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='manual',
            field=models.BooleanField(default=False),
        ),
    ]
