# Generated by Django 4.1 on 2023-11-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_equipo_manual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='numeroDeSerie',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
