# Generated by Django 4.1 on 2024-04-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_alter_equipo_numerodeserie'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='equipo',
            name='tipo_equipo',
            field=models.CharField(choices=[('EA', 'Equipo Alumnado'), ('EC', 'Equipo Clase'), ('PR', 'Proxector'), ('CA', 'Carro de carga'), ('PD', 'PDI'), ('PT', 'Pantalla táctil')], default='EA', max_length=2),
        ),
    ]
