# Generated by Django 4.1 on 2024-04-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0007_equipo_modelo_equipo_tipo_equipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='tipo_equipo',
            field=models.CharField(choices=[('EA', 'Equipo Alumnado'), ('EP', 'Equipo Profesorado'), ('EC', 'Equipo Clase'), ('PR', 'Proxector'), ('CA', 'Carro de carga'), ('PD', 'PDI'), ('PT', 'Pantalla táctil')], default='EA', max_length=2),
        ),
    ]
