# Generated by Django 3.2.7 on 2021-11-08 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0002_auto_20211022_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(blank=True, choices=[('A', 'Require Acción'), ('F', 'Espera Familias'), ('T', 'Espera Servicio Técnico'), ('P', 'Pechada')], default='A', max_length=1, null=True),
        ),
    ]
