# Generated by Django 3.2.7 on 2021-11-08 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0003_incidencia_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(choices=[('A', 'Require Acción'), ('F', 'Espera Familias'), ('T', 'Espera Servicio Técnico'), ('P', 'Pechada')], default='A', max_length=1),
        ),
    ]
